<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="test_process_coerce_bytes.py" name="test_process_coerce_bytes.TestProcessCoerceBytes-20230721092815" skipped="0" tests="1" time="0.001" timestamp="2023-07-21T09:28:15">
	<testcase classname="test_process_coerce_bytes.TestProcessCoerceBytes" file="spec/construct/test_process_coerce_bytes.py" line="8" name="test_process_coerce_bytes" time="0.001" timestamp="2023-07-21T09:28:15">
		<failure message="b'\xe8\xe8\xe8\xe8' != b'BBBB'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/tests/spec/construct/test_process_coerce_bytes.py", line 13, in test_process_coerce_bytes
    self.assertEqual(r.records[1].buf, b"\x42\x42\x42\x42")
AssertionError: b'\xe8\xe8\xe8\xe8' != b'BBBB'
]]>		</failure>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
