<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_index_to_param_eos.TestIndexToParamEos-20200831200214" tests="1" file="test_index_to_param_eos.py" time="0.001" timestamp="2020-08-31T20:02:14" failures="0" errors="1" skipped="0">
	<testcase classname="test_index_to_param_eos.TestIndexToParamEos" name="test_index_to_param_eos" time="0.001" timestamp="2020-08-31T20:02:14" file="spec/construct/test_index_to_param_eos.py" line="8">
		<error type="IndexError" message="list index out of range"><![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_index_to_param_eos.py", line 14, in test_index_to_param_eos
    self.assertEqual(r.blocks[0].buf, u"A")
IndexError: list index out of range
]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
