<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="test_process_repeat_bytes.py" name="test_process_repeat_bytes.TestProcessRepeatBytes-20220313103410" skipped="0" tests="1" time="0.001" timestamp="2022-03-13T10:34:10">
	<testcase classname="test_process_repeat_bytes.TestProcessRepeatBytes" file="spec/construct/test_process_repeat_bytes.py" line="8" name="test_process_repeat_bytes" time="0.001" timestamp="2022-03-13T10:34:10">
		<failure message="'\xec\xbb\xa3\x14\x8a' != 'r%=\x8a\x14'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_process_repeat_bytes.py", line 11, in test_process_repeat_bytes
    self.assertEqual(r.bufs[0], b"\x72\x25\x3D\x8A\x14")
AssertionError: '\xec\xbb\xa3\x14\x8a' != 'r%=\x8a\x14'
]]>		</failure>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
