<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_type_ternary.TestTypeTernary-20220318130518" tests="1" file="test_type_ternary.py" time="0.001" timestamp="2022-03-18T13:05:19" failures="1" errors="0" skipped="0">
	<testcase classname="test_type_ternary.TestTypeTernary" name="test_type_ternary" time="0.001" timestamp="2022-03-18T13:05:19" file="spec/construct/test_type_ternary.py" line="8">
		<failure type="AssertionError" message="102 != 101"><![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_type_ternary.py", line 10, in test_type_ternary
    self.assertEqual(r.dif.value, 101)
AssertionError: 102 != 101
]]></failure>
	</testcase>
</testsuite>
