<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="test_valid_fail_range_bytes.py" name="test_valid_fail_range_bytes.TestValidFailRangeBytes-20210206143518" skipped="0" tests="1" time="0.000" timestamp="2021-02-06T14:35:18">
	<testcase classname="test_valid_fail_range_bytes.TestValidFailRangeBytes" file="spec/python/test_valid_fail_range_bytes.py" line="9" name="test_valid_fail_range_bytes" time="0.000" timestamp="2021-02-06T14:35:18">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
