<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="test_eos_exception_u4.py" name="test_eos_exception_u4.TestEosExceptionU4-20230705162047" skipped="0" tests="1" time="0.000" timestamp="2023-07-05T16:20:47">
	<testcase classname="test_eos_exception_u4.TestEosExceptionU4" file="spec/python/test_eos_exception_u4.py" line="7" name="test_eos_exception_u4" time="0.000" timestamp="2023-07-05T16:20:47">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
