<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="test_eof_exception_u4.py" name="test_eof_exception_u4.TestEofExceptionU4-20200823214642" skipped="0" tests="1" time="0.000" timestamp="2020-08-23T21:46:43">
	<testcase classname="test_eof_exception_u4.TestEofExceptionU4" file="spec/python/test_eof_exception_u4.py" line="9" name="test_eof_exception_u4" time="0.000" timestamp="2020-08-23T21:46:43">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
