<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_eos_exception_u4.TestEosExceptionU4-20200628162531" tests="1" file="test_eos_exception_u4.py" time="0.000" timestamp="2020-06-28T16:25:31" failures="0" errors="0" skipped="0">
	<testcase classname="test_eos_exception_u4.TestEosExceptionU4" name="test_eos_exception_u4" time="0.000" timestamp="2020-06-28T16:25:31" file="spec/python/test_eos_exception_u4.py" line="9">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
