<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="test_debug_switch_user.py" name="test_debug_switch_user.TestDebugSwitchUser-20200111155723" skipped="0" tests="1" time="0.000" timestamp="2020-01-11T15:57:23">
	<testcase classname="test_debug_switch_user.TestDebugSwitchUser" file="spec/python/test_debug_switch_user.py" line="8" name="test_debug_switch_user" time="0.000" timestamp="2020-01-11T15:57:23">
		<error message="'DebugSwitchUser' object has no attribute 'code'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/python/test_debug_switch_user.py", line 11, in test_debug_switch_user
    self.assertEqual(r.code, 1)
AttributeError: 'DebugSwitchUser' object has no attribute 'code'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
